import type { Template } from '@/types';

export const EVENT = {
  name1: 'Rieke',
  name2: 'Her Future Husband',
  title: 'Rieke & Her Future Husband',
  subtitle: 'Engagement Moments',
  tagline: 'Capture the love, keep the moment',
};

export const templates: Template[] = [
  {
    id: 'plain',
    name: 'Plain',
    bg: '#ffffff',
    accent: '#2d1a26',
    text: '#2d1a26',
    frame: '#ffffff',
    label: 'Engagement 2026',
    showNames: false,
    variant: 'plain',
  },
  {
    id: 'thin',
    name: 'Thin',
    bg: '#fafafa',
    accent: '#ec407a',
    text: '#2d1a26',
    frame: '#ec407a',
    label: 'Rieke & Future Husband',
    showNames: true,
    variant: 'thin',
  },
  {
    id: 'thick',
    name: 'Bold',
    bg: '#fff5f8',
    accent: '#d6336c',
    text: '#b02a57',
    frame: '#ec407a',
    label: 'Forever Starts Here',
    showNames: true,
    variant: 'thick',
  },
  {
    id: 'polaroid',
    name: 'Polaroid',
    bg: '#f0f0f0',
    accent: '#2d1a26',
    text: '#2d1a26',
    frame: '#ffffff',
    label: 'Engagement 2026',
    showNames: false,
    variant: 'polaroid',
  },
  {
    id: 'double',
    name: 'Double',
    bg: '#ffffff',
    accent: '#c9a0a0',
    text: '#7a5c5c',
    frame: '#e8c4a0',
    label: 'A Love Story',
    showNames: true,
    variant: 'double',
  },
  {
    id: 'gradient',
    name: 'Blush',
    bg: '#1a1a2e',
    accent: '#ff9dc1',
    text: '#ffffff',
    frame: '#ff6fa3',
    label: 'Engagement Vibes',
    showNames: false,
    variant: 'gradient',
  },
  {
    id: 'dots',
    name: 'Dots',
    bg: '#f5ede0',
    accent: '#8b7355',
    text: '#5c4a32',
    frame: '#c9b896',
    label: 'A Love Story',
    showNames: true,
    variant: 'dots',
  },
  {
    id: 'shadow',
    name: 'Shadow',
    bg: '#1e2749',
    accent: '#ffd700',
    text: '#ffffff',
    frame: '#ffd700',
    label: 'A Night to Remember',
    showNames: false,
    variant: 'shadow',
  },
  {
    id: 'tape',
    name: 'Tape',
    bg: '#fff0e6',
    accent: '#ff9a76',
    text: '#c85a3e',
    frame: '#ffffff',
    label: 'Sweet Moments',
    showNames: true,
    variant: 'tape',
  },
  {
    id: 'art',
    name: 'Art',
    bg: '#0f0f1a',
    accent: '#ec407a',
    text: '#ffffff',
    frame: '#ec407a',
    label: 'RIEKE & FUTURE HUSBAND',
    showNames: false,
    variant: 'art',
  },
];

export function getTemplate(id: string): Template {
  return templates.find((t) => t.id === id) ?? templates[0];
}
