import type { Template } from '@/types';

export const EVENT = {
  name1: 'Rieke',
  name2: 'Her Future Husband',
  title: 'Rieke & Her Future Husband',
  subtitle: 'Engagement Moments',
  tagline: 'Capture the love, keep the moment',
};

export const templates: Template[] = [
  {
    id: 'classic',
    name: 'Classic',
    bg: '#ffffff',
    accent: '#ec407a',
    text: '#2d1a26',
    frame: '#ec407a',
    label: 'Rieke & Future Husband',
    showNames: true,
  },
  {
    id: 'blush',
    name: 'Blush',
    bg: '#fff5f8',
    accent: '#ff6fa3',
    text: '#b02a57',
    frame: '#ff9dc1',
    label: 'Engagement Vibes',
    showNames: false,
  },
  {
    id: 'rose-gold',
    name: 'Rose Gold',
    bg: '#fdf2e9',
    accent: '#c9a0a0',
    text: '#7a5c5c',
    frame: '#e8c4a0',
    label: 'Forever Starts Here',
    showNames: true,
  },
  {
    id: 'polaroid',
    name: 'Polaroid',
    bg: '#fafafa',
    accent: '#2d1a26',
    text: '#2d1a26',
    frame: '#ffffff',
    label: 'Engagement 2026',
    showNames: false,
  },
  {
    id: 'vintage',
    name: 'Vintage',
    bg: '#f5ede0',
    accent: '#8b7355',
    text: '#5c4a32',
    frame: '#c9b896',
    label: 'A Love Story',
    showNames: true,
  },
  {
    id: 'modern',
    name: 'Modern',
    bg: '#1a1a2e',
    accent: '#ff6fa3',
    text: '#ffffff',
    frame: '#ff6fa3',
    label: 'RIEKE & FUTURE HUSBAND',
    showNames: false,
  },
  {
    id: 'garden',
    name: 'Garden',
    bg: '#f0f7e9',
    accent: '#7a9b6e',
    text: '#3d5238',
    frame: '#a8c49a',
    label: 'Love in Bloom',
    showNames: true,
  },
  {
    id: 'midnight',
    name: 'Midnight',
    bg: '#1e2749',
    accent: '#ffd700',
    text: '#ffffff',
    frame: '#ffd700',
    label: 'A Night to Remember',
    showNames: false,
  },
  {
    id: 'peachy',
    name: 'Peachy',
    bg: '#fff0e6',
    accent: '#ff9a76',
    text: '#c85a3e',
    frame: '#ffbb99',
    label: 'Sweet Moments',
    showNames: true,
  },
  {
    id: 'minimal',
    name: 'Minimal',
    bg: '#ffffff',
    accent: '#2d1a26',
    text: '#2d1a26',
    frame: '#e0e0e0',
    label: 'Rieke ♥',
    showNames: false,
  },
];

export function getTemplate(id: string): Template {
  return templates.find((t) => t.id === id) ?? templates[0];
}
